sudo: true
language: node_js
node_js:
- '11'
cache: yarn
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
- export PATH="$HOME/.yarn/bin:$PATH"
- openssl aes-256-cbc -K $encrypted_f8957e202a83_key -iv $encrypted_f8957e202a83_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
- chmod 600 travis_rsa
- mv .travis/travis_rsa ~/.ssh/id_rsa
- cat .travis/server.pub >> $HOME/.ssh/known_hosts
jobs:
  include:
    - stage: build
      script: yarn build
    - stage: lint
      script: yarn lint
    - stage: deploy
      if: branch = master
      script: |
        ssh-add
        yarn build:client
        rsync -rq --delete -e 'ssh -p 4220' --rsync-path="rm -rf bicbacboe/staging/client && mkdir -p bicbacboe/staging/client && rsync" \
        $TRAVIS_BUILD_DIR/client/build/ travis@ssh.bicbacboe.com:bicbacboe/staging/client/
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"
