sudo: true
language: node_js
node_js:
  - '11'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - openssl aes-256-cbc -K $encrypted_f8957e202a83_key -iv $encrypted_f8957e202a83_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
  - chmod 600 .travis/travis_rsa
  - mv .travis/travis_rsa ~/.ssh/id_rsa
  - cat .travis/server.pub >> $HOME/.ssh/known_hosts
jobs:
  include:
    - stage: typecheck
      script: yarn run check
    # - stage: test
    #   script: yarn test
    - stage: lint
      script: yarn run lint
    - stage: Build & Deploy
      if: branch = master
      script:
        # Build the project
        - yarn run build
        # Upload the client build files
        - .travis/deploy.sh client
        # Upload the sever built files
        - .travis/deploy.sh server
# after_success:
#   - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#   - chmod +x send.sh
#   - "./send.sh success $WEBHOOK_URL"
# after_failure:
#   - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
#   - chmod +x send.sh
#   - "./send.sh failure $WEBHOOK_URL"
