language: node_js
node_js:
  - "11"
cache: yarn
jobs:
  include:
    - stage: build
      name: Build API
      script: yarn build:api
    - name: Build client
      script: yarn build:client
    - name: Build server
      script: yarn build:server
    # TODO: Test
    # TODO: allow fail
    - stage: lint
      name: Lint API
      script: yarn lint:api
    - name: Lint client
      script: yarn lint:client
    - name: Lint server
      script: yarn lint:server
    # TODO: Deploy